routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function ($router) {
    Route::get('/todos/new', 'TodoController@create')->name('todo-create');
    Route::post('/todos', 'TodoController@store')->name('todo-store');
    Route::get('/todos/{todo}/toggle-checked', 'TodoToggleCheckedController')->name('toggle-checked');

    Route::resource('tags', 'TagController');
});

app/Tag.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

/**
 * App\Tag
 *
 * @property int $id
 * @property string $label
 * @property string $color
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Todo[] $todos
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Tag newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Tag newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Tag query()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Tag whereColor($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Tag whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Tag whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Tag whereLabel($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Tag whereUpdatedAt($value)
 * @mixin \Eloquent
 */
class Tag extends Model {

    protected $fillable = ['label', 'color'];

    public function todos() {
        return $this->belongsToMany(Todo::class, 'todo_tag');
    }

}

app/Http/Controllers/TagController.php
<?php

namespace App\Http\Controllers;

use App\Tag;
use Illuminate\Http\Request;

class TagController extends Controller {
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() {
        $tags = Tag::withCount('todos')->get();

        return view('tag.index', ['tags' => $tags]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() {
        return view('tag.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request) {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Tag $tag
     *
     * @return \Illuminate\Http\Response
     */
    public function show(Tag $tag) {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Tag $tag
     *
     * @return \Illuminate\Http\Response
     */
    public function edit(Tag $tag) {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \App\Tag                 $tag
     *
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Tag $tag) {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Tag $tag
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy(Tag $tag) {
        //
    }
}

resources/views/tag/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Új címke</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    <div class="my-2 actions">
                        <a href="{{ route('tags.index') }}" class="btn btn-outline-secondary">Mégsem</a>
                    </div>

                    <form action="{{ route('todo-store') }}">
                        //
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/tag/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Címkék</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    <div class="my-2 actions">
                        <a href="{{ route('tags.create') }}" class="btn btn-outline-success">Új címke</a>
                        <a href="{{ route('home') }}" class="btn btn-outline-primary float-right">Teendők</a>
                    </div>

                    <div class="list-group">
                        @foreach($tags as $tag)
                        <a href="{{ route('tags.edit', ['tag' => $tag->id]) }}" class="list-group-item list-group-item-action">
                            <div class="d-flex w-100 justify-content-between">
                                <h5 class="mb-1">{{ $tag->label }} ({{ $tag->color }})</h5>
                                <small style="display: inline-block; width: 20px; height: 20px; overflow: hidden; background: {{ $tag->color }};">&nbsp;</small>
                            </div>
                        </a>
                        @endforeach
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection